# SurfaceDuoPkg CI build on VSTS

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    architecture: 'x64'
  displayName: Install correct Python

# Travis have this by default, because we preinstalled build-essentials
- script: sudo apt install uuid-dev
  displayName: 'Install VSTS dependencies'

# Fix-up directory link for VSTS, force replace current reference
- script: sudo ln -sfn $(pwd) ../SurfaceDuoPkg
  displayName: 'Fix directory links'

# Build iASL tool from repository
# Eventually we will just install prepackaged version
# - script: git clone https://github.com/acpica/acpica acpica-tools
#   displayName: 'Checkout ACPICA tools repository'

# - script: cd acpica-tools && make clean && make && sudo make install && cd ..
#   displayName: 'Build and install ACPICA tools'

- script: chmod +x ./setup_env.sh && sudo ./setup_env.sh
  displayName: 'Prepare pre-build environment, phase 0'

- script: pip install --upgrade -r ./pip-requirements.txt
  displayName: 'Prepare pre-build environment, phase 1'

- script: chmod +x ./build_releaseinfo.ps1 && ./build_releaseinfo.ps1
  displayName: 'Prepare pre-build environment, phase 2'

- script: chmod +x ./build_uefi.sh && ./build_uefi.sh -d all -s 6 && ./build_uefi.sh -d all -s 8
  displayName: 'UEFI build'

# Publish UEFI (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish SM8150 UEFI build'
  inputs:
    pathtoPublish: ./Build/*/*.img
    artifactName: SM8150 UEFI
